name: FTE News
favicon: null
layout_spectrum: 0.47112
typography_spectrum: 0.09508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#000000'
    - '#010101'
    - '#010101'
    - '#010101'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
