typography_spectrum: 0.09172
color:
  brandColors:
    - '#030303'
    - '#000000'
    - '#010101'
    - '#010101'
    - '#010101'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.64908
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/37107554-8d75-4126-afaf-57eec50197d7.png
name: FTE News
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
