name: FTE News
favicon: null
layout_spectrum: 0.64908
typography_spectrum: 0.0934
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#000000'
    - '#010101'
    - '#010101'
    - '#010101'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
