name: FTE Roster
favicon: null
layout_spectrum: 0.41417
typography_spectrum: 0.11183
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#000000'
    - '#010101'
    - '#010101'
    - '#010101'
  brandStrength: 0.75
  lightness: 0.9616982920560986
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
